name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update build env
      run: sudo apt-get update --fix-missing -y
    - name: install prerequisities
      run: sudo apt-get install libcups2-dev python3-dev gcc python3-setuptools
    - name: make
      run: make
    - name: sudo make install
      run: sudo make install
    - name: make dist
      run: make dist
    - name: python3 test.py
      run: python3 test.py
